language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
- npm run cover
- rm ./test/storage.json
before_install:
- openssl aes-256-cbc -K $encrypted_80f9505abc91_key -iv $encrypted_80f9505abc91_iv
  -in storage.json.enc -out ./test/storage.json -d
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"